version: "3.7"
services:
  mygameshop-api:
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile
    image: abdesousa/mypetshop-api
    ports:
      - 8090
    networks:
      - network1
 
networks:
  network1: